version: "3.9"

services:
  frontend:
    image: aifrak/svelte-sapper-in-action:latest
    build:
      context: .
      target: base
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    user: ${USER_UID:-1000}:${USER_GID:-1000}
    command: sleep infinity
    ports:
      # Port for svelte dev server
      - 5000:5000
      # Port for svelte live-reload
      - 35729:35729
    volumes:
      - .:/app
