version: "3.9"

services:
  app:
    image: aifrak/svelte-sapper-in-action:latest
    build:
      context: .
      target: base
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    user: ${USER_UID:-1000}:${USER_GID:-1000}
    command: sleep infinity
    ports:
      - 5000:5000
    volumes:
      - .:/app
