version: "3.9"

services:
  frontend:
    build:
      target: vscode
    volumes:
      - vscode:/home/app-user/.vscode-server/extensions
      - vscode-insiders:/home/app-user/.vscode-server-insiders/extensions

volumes:
  vscode:
  vscode-insiders:
